THREADS:
        16
fastq_out_dir:
        /mnt/morbo/Data/Public/Marklund_ENS/raw/
fasterq_flags:
        --split-files
        --include-technical
        -t /scratch/users/jared/sra_tmp
        -e 16

